### ISSUE TITLE
Weak vs Strong references for listeners

### ISSUE THREAD

**Issue by andreacalia** [ossgang/ossgang-commons#2]
Another point that might be worth discussing: Weak or Strong references for listeners? I see clear advantages for both:

- Strong references avoid situations where a listener is "silently" garbage collected because it is only loosely coupled to another class and no reference exist (the classic JAPC anonymous class listener thingy).

- Weak references would possibly simplify the interface (would we need an explicit unsubscribe in that case?), and it would make things simpler if we ever plan to introduce derived observables (e.g. Observable.map(...)). Also, it would avoid memory leaks in cases where "disposed" classes are still referenced in a listener (I think I had this once with lumiserver tasks and their subscriptions ...)

Any preference for one way or the other?

_Originally posted by @michi42 in https://github.com/ossgang/ossgang-commons/issues/1#issuecomment-504734970_

**Comment by kaifox** [comment]
I definitely would vote for strong refs as a default. All those weak listener stuff  in japc I find a horror. We could think of an option for weak references though ....

**Comment by michi42** [comment]
Implemented by the WEAK subscription option. Default is strong.
