### ISSUE TITLE
Switching between observables

### ISSUE THREAD

**Issue by kaifox** [ossgang/ossgang-commons#21]
Original proposal by @andreacalia :
```
Property<OverrideSelection> selectionSwitch = OverrideProperty.override(originalProperty).with(overrideProperty);

public enum OverrideSelection{ ORIGINAL, OVERRIDE }
```

**Comment by kaifox** [comment]
A few remarks: 
* I think the switching will only work nicely on observable(value)s, not on porperties ... as the bidi-thing would be very tricky...
* I think the final observable shall be of the same type than the original, but would need a 'side' input for switching .... All in all it is a bit tricky to formulate it in a readible form ....
* Further, there is a choice, if the 'switchin' channel shall be seen as a property where one should call set (upstream - this is what I interprete from andreas proposal), or as another  provided source (downstream), as in flux ....
At a first glance, the second one sounds a bit more consistent .... If preserving chaining like in flux, the equivalent to andreas proposal could look like:

```
ObservableValue<T> original;

ObservableValue<T> switched = original.switchOverride(ObservableValue<OverrideSelection> overrideSwitch, ObservableValue<T> alternative);
```

This could be expanded to N inputs, in the simplest case like
```
ObservableValue<T> switched = original.switchOverride(ObservableValue<Integer> switchIndex, ObservableValue<T> ... alternatives);
```
... or in a more complicated form:

```
ObservableValue<T> switched = original.switchOverride(ObservableValue<K> switchIndex, Map<K, T> switchingMap);
```

**Comment by michi42** [comment]
For the upstream subscription behavior, I would always keep all subscriptions and just forward the one value we need. First, this will prevent the subscribed-to observables from being GCd. Second, it makes it much easier to switch atomically (at least a "naive" subscribe/unsubscribe could introduce race conditions which would lead to dropped updates).

For the switching, I like most the Map approach - but I think you were missing an ObservableValue in the signature? I would take something like this:
```
ObservableValue<T> switched = ObservableValues.switch(ObservableValue<K> switchIndex, Map<K, ObservableValue<T>> switchingMap);
```
With the mechanisms we already have in Observables, we could expose another signature based on integer indices - but in general I would always prefer enum'd keys.
The original proposal would then just be a special case of that (with K = OverrideSelection).

**Comment by michi42** [comment]
Mostly solved by the DynamicConnectorObservableValue introduces in #25 I presume?

**Comment by andreacalia** [comment]
I think so. I close this one, anyway we can reopen it or create a new one in case we need to discuss something else :slightly_smiling_face:
