### ISSUE TITLE
Publishing Throwable in Properties

### ISSUE THREAD

**Issue by andreacalia** [ossgang/ossgang-commons#26]
We already had the need to publish an exception in a Property.

Imagine you have a property as field in a class that is exposed as ObservableValue. This is used as sink for data to start a "stream". In this scenario, sometimes it is necessary to publish an exception to notify the subscribers. It is possible that we're using the properties as they're not meant to be used ...

In my opinion we have a few options to choose from:
1. Add a `void set(Throwable exception)` in the `Property` interface.
2. Create another implementation of `Property` that has the `void set(Throwable exception)` method
3. In the `Property` interface have a `void set(Maybe<T>)` method as abstract and provide the `default void set(T)` as convenience method.
4. Create another interface that would be `Publisher<T>` or `Sink<T>` or ... with 2 methods:
```java
public class Publisher<T> {
  void publish(T value);
  void publish(Throwable exception);
}
```

I think the 4th option is the most decoupled one and provides more separation of concepts:
* Property: value-based entity (`#set`)
* EventSource: sending events (`#send`)
* Publisher: publishing values (`#publish`)

In the end they all are `Observable<T>` but the semantic is very clear :smile: 
Then the question would be if we could merge the `EventSource` with the `Publisher`, but I think we could keep both of them because they provide a very good and clear API.

What do you think? @michi42 @kaifox I'd like to push this through for this Sprint

**Comment by kaifox** [comment]
A few questions, that I understand the concepts:

1. what actually would be the difference between send and set? or send and publish? (I think I did not grab the EventSource right)
2. what would be the difference between publish(Throwable) and the currently available dispatch(Throwable) in DispatchingObservable?
3. would the publish() change the actual value of the property or not?

**Comment by kaifox** [comment]
Ok... I read a bit more sourcecode and I must admit that I did not follow the EventSource review properly.... I have the impression that we are growing to many very (!) similar concepts too fast (including my proposals!). I would suggest that we take a breath and look at what we have. 

1) Could one of you explain the above 3 different concepts, each in one paragraph ... their differences and their use-cases? (E.g. in the readme or github wiki or here in the issue, which we can then move to the readme) I am not so sure if they are fundamentally different.... 

2) I have a few comments on EventSource (sorry that I did not contribute them earlier):
2a) Why is there the word 'Event' in it? it is of type T, the same type as the values. In this sense, wouldnt it just be a ValueSource or just a Source? 
2b) I believe that interfaces have to be named by their purpose in the viewpoint of the intended user of the interface. As far as I see it, the currently so-called EventSource has the purpose for its user to send values downstream. Is this correct? So away from from him. So this interface is a **Sink not a Source**!
2c) Further argument in the direction of b): I believe it is a good idea to stay in our terms very close to reactive libraries. Having this said, I would like to refer to this: https://projectreactor.io/docs/core/release/api/reactor/core/publisher/FluxSink.html. It has an next() and error() method ... and isnt this what both of you want somehow?

**Comment by andreacalia** [comment]
Thanks for the inputs Kajetan!
We quickly discussed with Michi and the pull request #27 will contain the proposed solution :smile: 

In the end you're right, we're exploding the interfaces to provide a nice semantic to the user. The Sink idea brings us closer to the reactive world and an `ObservableValueSink` will also serve the use case of the `EventSource` :relaxed:

**Comment by kaifox** [comment]
Cool ;-)

**Comment by andreacalia** [comment]
PR merged
