### ISSUE TITLE
Observables subscribe & unsubscribe

### ISSUE THREAD

**Issue by andreacalia** [ossgang/ossgang-commons#3]
From #1 :
1. `unsubscribe(Consumer<T>)` on the interface
2. `public Subscription subscribe(Consumer<T>)` and use the `Subscription` to unsubscribe?

I would probably prefer the second approach (reactive-stream style)

**Comment by michi42** [comment]
OK for me. However, I think you should not be required to keep a reference to Subscription if you don't want to unsubscribe (which is a quite common case when you wire spring singletons...) - not like the JAPC SubscriptionHandle which kills the subscription when it goes out of scope and is GC'd.

**Comment by kaifox** [comment]
I agree, keeping a referece to the subscription should be optional ... I would tend to try to avoid "weak listener magic".... 
This would somehow be a pattern, like the disposable in rx stream, or?

**Comment by andreacalia** [comment]
> I agree, keeping a referece to the subscription should be optional ... I would tend to try to avoid "weak listener magic"....
> This would somehow be a pattern, like the disposable in rx stream, or?

Yes :smile:

**Comment by michi42** [comment]
For now, we return a Subscription object which allows to unsubscribe - but can be safely discarded.

**Comment by andreacalia** [comment]
Ok, closing the issue :smile:
