### ISSUE TITLE
Change Listeners

### ISSUE THREAD

**Issue by kaifox** [ossgang/ossgang-commons#4]
In the context of properties, I think we said, we want change listeners ... so potentially, we could introduce this in parallel to Observable as e.g. `ChangeObservable`?

```
interface ChangeObservable<T> {
Subscription subscribe(ChangeListener<T> listener);
}

interface ChangeListener<T> {  // Or use a biconsumer?
void valueChanged(T oldValue, T newValue);
}
```

**Comment by michi42** [comment]
Hmm, where did we need this? I think I always hated the JavaFX listeners with way too many parameters, and liked the simplicity of a simple consumer - but of course we could make it as another option ;-)
Maybe I just forgot...

What I think we were discussing at some point (and maybe for that we would need the previous value?) was some kind of "vetoable" change listener, that can e.g. prevent a property from being set to an "invalid" value BEFORE regular listeners get notified.

**Comment by michi42** [comment]
Implemented by the ON_CHANGE option.
