### ISSUE TITLE
Don't use Maybe#attempt on the Uncheckeds

### ISSUE THREAD

**Issue by andreacalia** [ossgang/ossgang-commons#44]
Don't use Maybes in the Unchecked methods since the values of the function/consumer may be null and it may be a valid case. Move to standard try/catch

https://github.com/ossgang/ossgang-commons/blob/848de098d0bd279c6709e426c35da5df805c4991/src/main/java/org/ossgang/commons/utils/Uncheckeds.java#L22-L24

https://github.com/ossgang/ossgang-commons/blob/848de098d0bd279c6709e426c35da5df805c4991/src/main/java/org/ossgang/commons/utils/Uncheckeds.java#L30-L32

**Comment by michi42** [comment]
Or more general - should we allow creation of nullable maybes and treat null as a valid value, like we do for void maybes?
Something like Maybe.ofNullableValue()?

**Comment by andreacalia** [comment]
I believed one of the main points about the design of the Maybes is that by contract the values are never null.. I would not change it at the moment since it saves you null checks and NPEs (unless the Maybe is of type Void of course).

Maybe we can discuss this further in another issue since we need some brainstorming if we want to change it.
After using it a bit I find the distinction between Void an non-Void very nice, but we have funny situations e.g., `Maybe.<Void>ifPresent(Consumer<Void>)` instead of a nicer `Runnable` since the value will always be null.
I don't think we can do too much about this due to the limitations of the type system (we could duplicate the classes Maybe and VoidMaybe but I don't know if it's worth it and if it fixes all the issues).

**Comment by michi42** [comment]
Yes, we should not rush it ... but in general I do see a few cases where it might be useful. On the other hand, you can always explicitly use a `Maybe<Optional<T>>` in these situations (which makes it very explicit that the value can be absent)

For the Void maybe, there are some methods like Maybe.then() which take runnables ... these can be used for Void maybes to avoid discarding the argument ...
